name: Glitch Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '486e3231-89f8-4a40-9e9f-1cb319aaa9be'
        auth-token: '0cf99ada-1560-4cf2-aea0-64943aea12bb'
